<<<<<<< HEAD
# Generated by Django 4.0.5 on 2022-06-27 16:37
=======
# Generated by Django 4.0.5 on 2022-06-27 14:41
>>>>>>> 1ebbf31daafbc5ee37967331a558b96b76b8e28c

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='BlogName')),
            ],
            options={
                'verbose_name': 'BlogName',
                'verbose_name_plural': 'BlogNames',
=======
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
>>>>>>> 1ebbf31daafbc5ee37967331a558b96b76b8e28c
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='BlogCategory')),
                ('category', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.blog', verbose_name='category')),
            ],
            options={
                'verbose_name': 'BlogCategory',
                'verbose_name_plural': 'BlogCategories',
=======
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Назва')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.blog', verbose_name='Назва блогу')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
>>>>>>> 1ebbf31daafbc5ee37967331a558b96b76b8e28c
            },
        ),
    ]
