# Generated by Django 4.0.5 on 2022-06-27 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'verbose_name': 'Назва', 'verbose_name_plural': 'Назви'},
        ),
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва'),
        ),
        migrations.CreateModel(
            name='AdvertCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Ім'я")),
                ('category', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='adverts.advert', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': "Ім'я",
                'verbose_name_plural': 'Імена',
            },
        ),
    ]
