# Generated by Django 4.0.5 on 2022-06-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_alter_advert_options_alter_advert_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'verbose_name': 'Пропозиція', 'verbose_name_plural': 'Пропозиції'},
        ),
        migrations.AlterModelOptions(
            name='advertcategory',
            options={'verbose_name': 'Назва пропозиції', 'verbose_name_plural': 'Назва пропозицій'},
        ),
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Пропозиція'),
        ),
        migrations.AlterField(
            model_name='advertcategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва пропозиції'),
        ),
    ]
