# Generated by Django 4.0.5 on 2022-06-30 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_alter_advert_options_alter_advertcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('advert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adverts.advert')),
            ],
            options={
                'verbose_name': 'Advert feature',
                'verbose_name_plural': 'Advert features',
            },
        ),
    ]
