# Generated by Django 4.0.5 on 2022-06-27 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adverts', '0003_alter_advert_options_alter_advertcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'verbose_name': 'Advert', 'verbose_name_plural': 'Adverts'},
        ),
        migrations.AlterModelOptions(
            name='advertcategory',
            options={'verbose_name': 'AdvertCategory', 'verbose_name_plural': 'AdvertCategories'},
        ),
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Advert'),
        ),
        migrations.AlterField(
            model_name='advertcategory',
            name='category',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='adverts.advert', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='advertcategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AdvertCategory'),
        ),
        migrations.CreateModel(
            name='AdvertResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Titles',
            },
        ),
    ]
